
#ACTUATOR configurator
##1- Endpoints a exponer helth, info, metrics, etc.
    management.endpoints.web.exposure.include=health,info,beans,mappings
##2- Endpoints que no se van a exponer.
    management.endpoints.web.exposure.exclude=metrics
##3- Habilitar que se devuelva info de variables de entorno
    management.info.env.enabled=true
#Security configuration for actuator endpoints


#Information about the application
spring.application.name=PlannerManagement
info.app.name=PlannerManagementApi
info.app.description=Application for managing social planners
info.app.version=${project.version}
info.app.author= Cristina Saleta
api.version=v1
#Configuration about the server
server.port=8080

#Database initialization configuration
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/friendapp_db
spring.datasource.username=admin
spring.datasource.password=password123
